name: .NET Build, Test and Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Add permissions configuration
permissions:
  contents: write
  packages: write

env:
  SOLUTION_PATH: SimpleMapper/SimpleMapper.sln
  PACKAGE_PROJECT_PATH: SimpleMapper/SimpleMapper/SimpleMapper.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
  build-and-pack:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for tag history

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release

      - name: Create output directory
        run: mkdir -p ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Pack
        run: dotnet pack ${{ env.PACKAGE_PROJECT_PATH }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg
          if-no-files-found: error

  publish:
    name: Publish to NuGet
    needs: build-and-pack
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Run on push to main branch
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push \
            "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg" \
            --api-key $NUGET_API_KEY \
            --source ${{ env.NUGET_SOURCE_URL }} \
            --skip-duplicate
